### ISSUE TITLE
Support for structstatus

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [larsOhne/conditional_style#1]
Hi,

how can I query the status values that are processed using the Structstatus plugin?

Regards
Juergen

**Comment by larsOhne** [comment]
Hi Jürgen,
could you explain in more detail, what you have problems with? Maybe add a code snippet ;)

**Comment by Juergen-aus-Zuendorf** [comment]
For testing I have a query that looks like this:
```
---- struct table ----
schema     : cms_meta
cols       : %title%, cms-bereiche, cms-bereiche-u, cms-benennung, cms-serie, cms-modultyp, cms-modulbeschreibung, cms-status
filter     : cms-modultyp =* ^((?!qverw|hinw|fragm|liefn|tabel).)*$
  and      : cms-status   <> ungültig
condstyle  : cms-modulbeschreibung contains Bedienung ? "color: steelblue;" : "color: red;"
----

```
And that works fine. The query refers to "cms-module-description" which is a text field.

But if I want to query about the status field it doesn't work:
```
condstyle  : cms-status = aktuell ? "color: steelblue;" : "color: red;"
```
Here the query refers to "cms-status" which is a field of the type "status" from the [structstatus](https://www.dokuwiki.org/plugin:structstatus) plugin.

By the way the same problem I get when I query fields of the [structjoin](https://www.dokuwiki.org/plugin:structjoin) plugin.
